/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author junhyeok
 */

import java.sql.*;

public class mainFrame extends javax.swing.JFrame {

    public mainFrame() {
        initComponents();
    }
    boolean passwordCheck = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameCheckTrue = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        btnNameCheckTrueExit = new javax.swing.JButton();
        nameCheckFalse = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        btnNameCheckFalseExit = new javax.swing.JButton();
        joinTrue = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        btnJoinTrueExit = new javax.swing.JButton();
        joinFalse = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnJoinFalseExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPasswordCheck = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblc = new javax.swing.JLabel();
        lblquf = new javax.swing.JLabel();
        RadioBtnRegular = new javax.swing.JRadioButton();
        RadioBtnAssociate = new javax.swing.JRadioButton();
        RadioBtnStudent = new javax.swing.JRadioButton();
        boxSwimming = new javax.swing.JCheckBox();
        boxSki = new javax.swing.JCheckBox();
        boxReading = new javax.swing.JCheckBox();
        boxGame = new javax.swing.JCheckBox();
        boxGolf = new javax.swing.JCheckBox();
        boxTennis = new javax.swing.JCheckBox();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordCheck = new javax.swing.JPasswordField();
        btnJoin = new javax.swing.JButton();
        btnCheckId = new javax.swing.JButton();

        nameCheckTrue.setTitle("중복체크");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("사용가능한 아이디입니다.");

        btnNameCheckTrueExit.setText("확인");
        btnNameCheckTrueExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameCheckTrueExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nameCheckTrueLayout = new javax.swing.GroupLayout(nameCheckTrue.getContentPane());
        nameCheckTrue.getContentPane().setLayout(nameCheckTrueLayout);
        nameCheckTrueLayout.setHorizontalGroup(
            nameCheckTrueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameCheckTrueLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameCheckTrueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNameCheckTrueExit)
                .addContainerGap())
        );
        nameCheckTrueLayout.setVerticalGroup(
            nameCheckTrueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameCheckTrueLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnNameCheckTrueExit)
                .addContainerGap())
        );

        nameCheckFalse.setTitle("중복체크");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("아이디 중복입니다.");

        btnNameCheckFalseExit.setText("확인");
        btnNameCheckFalseExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameCheckFalseExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nameCheckFalseLayout = new javax.swing.GroupLayout(nameCheckFalse.getContentPane());
        nameCheckFalse.getContentPane().setLayout(nameCheckFalseLayout);
        nameCheckFalseLayout.setHorizontalGroup(
            nameCheckFalseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameCheckFalseLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameCheckFalseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNameCheckFalseExit)
                .addContainerGap())
        );
        nameCheckFalseLayout.setVerticalGroup(
            nameCheckFalseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameCheckFalseLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnNameCheckFalseExit)
                .addContainerGap())
        );

        joinTrue.setTitle("중복체크");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("회원가입 성공");

        btnJoinTrueExit.setText("확인");
        btnJoinTrueExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinTrueExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinTrueLayout = new javax.swing.GroupLayout(joinTrue.getContentPane());
        joinTrue.getContentPane().setLayout(joinTrueLayout);
        joinTrueLayout.setHorizontalGroup(
            joinTrueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinTrueLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinTrueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnJoinTrueExit)
                .addContainerGap())
        );
        joinTrueLayout.setVerticalGroup(
            joinTrueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinTrueLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnJoinTrueExit)
                .addContainerGap())
        );

        joinFalse.setTitle("중복체크");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("회원가입 실패");

        btnJoinFalseExit.setText("확인");
        btnJoinFalseExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinFalseExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinFalseLayout = new javax.swing.GroupLayout(joinFalse.getContentPane());
        joinFalse.getContentPane().setLayout(joinFalseLayout);
        joinFalseLayout.setHorizontalGroup(
            joinFalseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinFalseLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinFalseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnJoinFalseExit)
                .addContainerGap())
        );
        joinFalseLayout.setVerticalGroup(
            joinFalseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinFalseLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnJoinFalseExit)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("회원 가입(Oracle)");

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("아이디");

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("비밀번호");

        lblPasswordCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasswordCheck.setText("비밀번호 확인");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("성   명");

        lblc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblc.setText("회원 구분");

        lblquf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblquf.setText("관심 분야");

        buttonGroup1.add(RadioBtnRegular);
        RadioBtnRegular.setSelected(true);
        RadioBtnRegular.setText("정회원");

        buttonGroup1.add(RadioBtnAssociate);
        RadioBtnAssociate.setText("준회원");

        buttonGroup1.add(RadioBtnStudent);
        RadioBtnStudent.setText("학생회원");

        boxSwimming.setText("수영");

        boxSki.setText("스키");

        boxReading.setText("독서");

        boxGame.setText("게임");

        boxGolf.setText("골프");

        boxTennis.setText("테니스");

        btnJoin.setText("회원 가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        btnCheckId.setText("중복 확인");
        btnCheckId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnJoin)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblquf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPasswordCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPassword)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPasswordCheck))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCheckId))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxSki)
                                            .addComponent(boxSwimming))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxReading)
                                            .addComponent(boxGame))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boxTennis)
                                            .addComponent(boxGolf)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioBtnRegular)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioBtnAssociate)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioBtnStudent)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordCheck)
                    .addComponent(txtPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblc)
                    .addComponent(RadioBtnRegular)
                    .addComponent(RadioBtnAssociate)
                    .addComponent(RadioBtnStudent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblquf)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxSwimming)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxSki))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxReading))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxGolf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxTennis)))
                .addGap(8, 8, 8)
                .addComponent(btnJoin)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIdActionPerformed
        String sql = "SELECT * FROM users WHERE userId = ?";
        
        String userId = txtId.getText();
        System.out.println(txtId.getText());
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        try {
            conn = DBConn.getConnection();
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, userId);
            
            rs = pstmt.executeQuery();
            if(rs.next()) {
                if(rs.getString("userId").equals(userId)) {
                    System.out.println("아이디 중복");
                    passwordCheck = false;
                } else {
                    passwordCheck = true;
                }
            } else {
                passwordCheck = true;
            }
            
        } catch(Exception e) {
            System.out.println("passwordCheck 실패");
            System.out.println(e.getMessage());
        } finally {
            try {
                if(rs != null) rs.close();
                if(pstmt != null) pstmt.close();
                if(conn != null) conn.close();
            } catch(Exception e) {
                System.out.println("DB 연결 해제 실패 (btnCheckIdAction)");
                System.out.println(e.getMessage());
            }
        }
        if(passwordCheck == true) {
            nameCheckTrue.setLocation(350, 350);  // Modal 대화 상자 위치 지정
            nameCheckTrue.setSize(320, 160);  // Modal 대화상자 크기 지정
            nameCheckTrue.show();
        } else {
            nameCheckFalse.setLocation(350, 350);  // Modal 대화 상자 위치 지정
            nameCheckFalse.setSize(320, 160);  // Modal 대화상자 크기 지정
            nameCheckFalse.show();
        }
        System.out.println(passwordCheck);
    }//GEN-LAST:event_btnCheckIdActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        
        if (passwordCheck == false) {
            System.out.println("중복체크해 주십시오.");
        } else {
            String password = null;
            password += txtPassword.getPassword();

            String strMemberData = null;
            if(RadioBtnRegular.isSelected()) // 정회원 선택시 
                strMemberData = RadioBtnRegular.getText() + " "; // 정회원 입력 
            if(RadioBtnAssociate.isSelected()) // 준회원 선택시 
                strMemberData = RadioBtnAssociate.getText() + " "; // 준회원 입력 
            if(RadioBtnStudent.isSelected()) // 학생 회원 선택시
                strMemberData = RadioBtnStudent.getText() + " "; // 학생 회원 입력 

            // bit 입력
            int bit = 0;
            if(boxSwimming.isSelected())   bit += 32;      // 수영 = 32bit
            if(boxGame.isSelected())       bit += 16;      // 게임 = 16bit
            if(boxGolf.isSelected())       bit += 8;       // 골프 = 8bit
            if(boxSki.isSelected())        bit += 4;       // 스키 = 4bit
            if(boxReading.isSelected())    bit += 2;       // 독서 = 2bit
            if(boxTennis.isSelected())     bit += 1;       // 테니스 = 1bit


            String sql = "INSERT INTO Users VALUES (?, ?, ?, ?, ?)";

            Connection conn = null;
            PreparedStatement pstmt = null;
            ResultSet rs = null;
            try {
                conn = DBConn.getConnection();
                pstmt = conn.prepareStatement(sql);

                pstmt.setString(1, txtId.getText());
                pstmt.setString(2, password);
                pstmt.setString(3, txtName.getText());
                pstmt.setString(4, strMemberData);
                pstmt.setInt(5, bit);

                rs = pstmt.executeQuery();
                System.out.println("회원가입 성공");
                joinTrue.setLocation(350, 350);  // Modal 대화 상자 위치 지정
                joinTrue.setSize(320, 160);  // Modal 대화상자 크기 지정
                joinTrue.show();
            } catch(Exception e) {
                System.out.println("join 실패");
                System.out.println(e.getMessage());
                joinFalse.setLocation(350, 350);  // Modal 대화 상자 위치 지정
                joinFalse.setSize(320, 160);  // Modal 대화상자 크기 지정
                joinFalse.show();
            } finally {
                try {
                    if(rs != null) rs.close();
                    if(pstmt != null) pstmt.close();
                    if(conn != null) conn.close();
                } catch(Exception e) {
                    System.out.println("DB 연결 해제 실패 (btnJoinAction)");
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnNameCheckTrueExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameCheckTrueExitActionPerformed
        nameCheckTrue.dispose();
    }//GEN-LAST:event_btnNameCheckTrueExitActionPerformed

    private void btnNameCheckFalseExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameCheckFalseExitActionPerformed
        nameCheckFalse.dispose();
    }//GEN-LAST:event_btnNameCheckFalseExitActionPerformed

    private void btnJoinTrueExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinTrueExitActionPerformed
        joinTrue.dispose();
    }//GEN-LAST:event_btnJoinTrueExitActionPerformed

    private void btnJoinFalseExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinFalseExitActionPerformed
        joinFalse.dispose();
    }//GEN-LAST:event_btnJoinFalseExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioBtnAssociate;
    private javax.swing.JRadioButton RadioBtnRegular;
    private javax.swing.JRadioButton RadioBtnStudent;
    private javax.swing.JCheckBox boxGame;
    private javax.swing.JCheckBox boxGolf;
    private javax.swing.JCheckBox boxReading;
    private javax.swing.JCheckBox boxSki;
    private javax.swing.JCheckBox boxSwimming;
    private javax.swing.JCheckBox boxTennis;
    private javax.swing.JButton btnCheckId;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnJoinFalseExit;
    private javax.swing.JButton btnJoinTrueExit;
    private javax.swing.JButton btnNameCheckFalseExit;
    private javax.swing.JButton btnNameCheckTrueExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JDialog joinFalse;
    private javax.swing.JDialog joinTrue;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordCheck;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblc;
    private javax.swing.JLabel lblquf;
    private javax.swing.JDialog nameCheckFalse;
    private javax.swing.JDialog nameCheckTrue;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordCheck;
    // End of variables declaration//GEN-END:variables
}
