/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author junhyeok
 */

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class loginForm extends javax.swing.JFrame {

    boolean boolJoin = false;
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JoinFrame = new javax.swing.JFrame();
        lblJoinTitle = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblUserPWD = new javax.swing.JLabel();
        lblUserPWDCheck = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtUserID = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        txtUserPWD = new javax.swing.JPasswordField();
        txtUserPWDCheck = new javax.swing.JPasswordField();
        btnCheckID = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblLoginTitle = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblRootID = new javax.swing.JLabel();
        lblRootPWD = new javax.swing.JLabel();
        txtRootID = new javax.swing.JTextField();
        btnRootLogin = new javax.swing.JButton();
        btnJoinForm = new javax.swing.JButton();
        txtRootPWD = new javax.swing.JPasswordField();

        lblJoinTitle.setText("회원가입 창");

        lblUserID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserID.setText("아이디 : ");

        lblUserPWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserPWD.setText("비밀번호 : ");

        lblUserPWDCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserPWDCheck.setText("비밀번호 확인 : ");

        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("이름 : ");

        lblUserEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserEmail.setText("이메일 : ");

        btnJoin.setText("회원가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        btnCancle.setText("취소");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        btnCheckID.setText("중복 확인");
        btnCheckID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JoinFrameLayout = new javax.swing.GroupLayout(JoinFrame.getContentPane());
        JoinFrame.getContentPane().setLayout(JoinFrameLayout);
        JoinFrameLayout.setHorizontalGroup(
            JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JoinFrameLayout.createSequentialGroup()
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JoinFrameLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblJoinTitle))
                    .addGroup(JoinFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUserEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserPWD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserPWDCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JoinFrameLayout.createSequentialGroup()
                                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCheckID))
                            .addComponent(txtUserEmail)
                            .addComponent(txtUserPWDCheck)
                            .addComponent(txtUserPWD)
                            .addComponent(txtUserName))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JoinFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoin)
                .addContainerGap())
        );
        JoinFrameLayout.setVerticalGroup(
            JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JoinFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblJoinTitle)
                .addGap(24, 24, 24)
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPWD)
                    .addComponent(txtUserPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPWDCheck)
                    .addComponent(txtUserPWDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserEmail)
                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(JoinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoin)
                    .addComponent(btnCancle))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RootLoginFrame");

        btnExit.setText("종료");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblLoginTitle.setText("포스기");

        lblDetail.setText("관리자 로그인");

        lblStudentName.setText("이준혁, 한재근");

        lblRootID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRootID.setText("관리자 아이디 : ");

        lblRootPWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRootPWD.setText("관리자 비밀번호 : ");

        btnRootLogin.setText("로그인");
        btnRootLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootLoginActionPerformed(evt);
            }
        });

        btnJoinForm.setText("회원가입");
        btnJoinForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblLoginTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRootID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRootPWD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRootID)
                            .addComponent(txtRootPWD)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 170, Short.MAX_VALUE)
                        .addComponent(btnJoinForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRootLogin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStudentName)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLoginTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblDetail)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRootID)
                            .addComponent(txtRootID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRootPWD)
                            .addComponent(txtRootPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblStudentName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRootLogin)
                    .addComponent(btnJoinForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRootLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootLoginActionPerformed
        String rootId = txtRootID.getText();
        String rootPWD = null;
        rootPWD += txtRootPWD.getPassword();
        
        User user = new User();
        UserDAO userDAO = new UserDAO();
        
        user = userDAO.login(rootId, rootPWD);
        if(user == null) {
            System.out.println("로그인 실패");
            JOptionPane.showMessageDialog(null, "아이디와 비밀번호를 확인해 주십시오.", "경고", JOptionPane.ERROR_MESSAGE);
        } else {
            System.out.println("로그인 성공");
            JOptionPane.showMessageDialog(null, "로그인 성공");
        }
    }//GEN-LAST:event_btnRootLoginActionPerformed

    private void btnJoinFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinFormActionPerformed
        JoinFrame.setSize(410, 300);
        JoinFrame.show();
    }//GEN-LAST:event_btnJoinFormActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        JoinFrame.dispose();
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnCheckIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIDActionPerformed
        UserDAO userDAO = new UserDAO();
        
        String userID = txtUserID.getText();
        if(userID == null || userID.equals("")){
            JOptionPane.showMessageDialog(null, "아이디를 입력해 주십시오.", "경고", JOptionPane.ERROR_MESSAGE);
        } else {
            int result = userDAO.idCheck(userID);
            if(result == 1) {
                System.out.println("사용할 수 있는 ID");
                JOptionPane.showMessageDialog(null, "사용할 수 있는 ID");
                boolJoin = true;
            } else {
                System.out.println("아이디 중복");
                JOptionPane.showMessageDialog(null, "아이디 중복", "경고", JOptionPane.ERROR_MESSAGE);

            }
        }        
    }//GEN-LAST:event_btnCheckIDActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        if(boolJoin == false) {
            System.out.println("ID 중복 확인 먼저 해 주십시오.");
            JOptionPane.showMessageDialog(null, "ID 중복 확인 먼저 해 주십시오.", "경고", JOptionPane.ERROR_MESSAGE);
        } else {
            String userName = txtUserName.getText();
            String userID = txtUserID.getText();
            String userPWD = null;
            userPWD += txtUserPWD.getPassword();
            String userEmail = txtUserEmail.getText();
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            String userCreated = dateFormat.format(date);
            
            User user = new User(userName, userID, userPWD, userEmail, userCreated);
            UserDAO userDAO = new UserDAO();
            
            int result = userDAO.join(user);
            if(result != 1) {
                System.out.println("회원가입 실패");
                JOptionPane.showMessageDialog(null, "회원가입 실패", "경고", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println("회원가입 성공");
                JOptionPane.showMessageDialog(null, "회원가입 성공");
            }
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JoinFrame;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnCheckID;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnJoinForm;
    private javax.swing.JButton btnRootLogin;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblJoinTitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblRootID;
    private javax.swing.JLabel lblRootPWD;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPWD;
    private javax.swing.JLabel lblUserPWDCheck;
    private javax.swing.JTextField txtRootID;
    private javax.swing.JPasswordField txtRootPWD;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPWD;
    private javax.swing.JPasswordField txtUserPWDCheck;
    // End of variables declaration//GEN-END:variables
}
