/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author junhyeok
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JOptionPane;


public class Member_MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Member_MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        TextFieldName = new javax.swing.JTextField();
        RadioBtnRegular = new javax.swing.JRadioButton();
        RadioBtnAssociate = new javax.swing.JRadioButton();
        RadioBtnStudent = new javax.swing.JRadioButton();
        CheckBoxSwimming = new javax.swing.JCheckBox();
        CheckBoxGame = new javax.swing.JCheckBox();
        CheckBoxGolf = new javax.swing.JCheckBox();
        CheckBoxTennis = new javax.swing.JCheckBox();
        CheckBoxReading = new javax.swing.JCheckBox();
        CheckBoxSki = new javax.swing.JCheckBox();
        btnOverlap = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("회원 가입");

        jLabel2.setText("아이디");

        jLabel3.setText("비밀번호");

        jLabel4.setText("비밀번호 확인");

        jLabel5.setText("성 명");

        jLabel6.setText("회원 구분");

        jLabel7.setText("관심 분야");

        RadioBtnRegular.setText("정회원");

        RadioBtnAssociate.setText("준회원");

        RadioBtnStudent.setText("학생회원");

        CheckBoxSwimming.setText("수영");

        CheckBoxGame.setText("게임");

        CheckBoxGolf.setText("골프");

        CheckBoxTennis.setText("테니스");

        CheckBoxReading.setText("독서");

        CheckBoxSki.setText("스키");

        btnOverlap.setText("중복 확인");
        btnOverlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverlapActionPerformed(evt);
            }
        });

        btnJoin.setText("회원 가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        jLabel8.setText("직 업");

        jLabel9.setText("결재 방법");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "학생", "회사원(연구 개발)", "회사원(사무직)", "회사원(마케팅)", "자영업자", "공무원", "기타" }));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "현금", "카드", "포인트" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOverlap))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(RadioBtnRegular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtnAssociate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtnStudent))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CheckBoxSwimming)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBoxGame)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBoxGolf))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CheckBoxSki)
                                            .addGap(18, 18, 18)
                                            .addComponent(CheckBoxReading)
                                            .addGap(18, 18, 18)
                                            .addComponent(CheckBoxTennis))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnJoin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOverlap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RadioBtnRegular)
                    .addComponent(RadioBtnAssociate)
                    .addComponent(RadioBtnStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CheckBoxSwimming)
                    .addComponent(CheckBoxGame)
                    .addComponent(CheckBoxGolf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxSki)
                    .addComponent(CheckBoxReading)
                    .addComponent(CheckBoxTennis))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnJoin))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOverlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverlapActionPerformed
        try {
            FileReader tr = new FileReader("/Users/hansohee/inhatc/2학년 2학기/Java_Project/과제/member.txt"); //경로
            BufferedReader fileRead = new BufferedReader(tr);
            String strMember;
            
            while((strMember = fileRead.readLine()) != null) {
                String[] id = strMember.split(" ");
                if(!TextFieldID.getText().equals(id[0])) {
                    JOptionPane.showMessageDialog(null, "사용 가능한 아이디입니다.");
                } else {
                    JOptionPane.showMessageDialog(null, "중복된 아이디입니다.");
                }
            }
            fileRead.close();
        } catch(FileNotFoundException ex) {
          JOptionPane.showMessageDialog(null, "member.txt를 찾을 수 없습니다.");
        } catch(IOException ex) {
            
        }
    }//GEN-LAST:event_btnOverlapActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        String strMemberData = null;
        
        try {
            FileWriter fw = new FileWriter("/Users/hansohee/inhatc/2학년 2학기/Java_Project/과제/member.txt", true);
            BufferedWriter fileWrite = new BufferedWriter(fw);
            
            if(!Arrays.equals(jPasswordField1.getPassword(), jPasswordField2.getPassword())) {
                JOptionPane.showMessageDialog(null, "비밀번호가 일치하지 않습니다.");
            } else {
                strMemberData = TextFieldID.getText() + " ";     // ID 입력
                strMemberData += jPasswordField1.getPassword() + " ";    // Password 입력 
                strMemberData += TextFieldName.getText() + " ";  // 성명 입력
                
                // 회원 입력
                if(RadioBtnRegular.isSelected()) // 정회원 선택시 
                    strMemberData += RadioBtnRegular.getText() + " "; // 정회원 입력 
                if(RadioBtnAssociate.isSelected()) // 준회원 선택시 
                    strMemberData += RadioBtnAssociate.getText() + " "; // 준회원 입력 
                if(RadioBtnStudent.isSelected()) // 학생 회원 선택시
                    strMemberData += RadioBtnStudent.getText() + " "; // 학생 회원 입력 
                
                // bit 입력
                int bit = 0;
                if(CheckBoxSwimming.isSelected())   bit += 32;      // 수영 = 32bit
                if(CheckBoxGame.isSelected())       bit += 16;      // 게임 = 16bit
                if(CheckBoxGolf.isSelected())       bit += 8;       // 골프 = 8bit
                if(CheckBoxSki.isSelected())        bit += 4;       // 스키 = 4bit
                if(CheckBoxReading.isSelected())    bit += 2;       // 독서 = 2bit
                if(CheckBoxTennis.isSelected())     bit += 1;       // 테니스 = 1bit
                strMemberData += bit + " "; // 총 bit 입력
                
                strMemberData += jComboBox1.getSelectedItem().toString() + " ";
                strMemberData += jList1.getSelectedValue() + "\n";
                
                fileWrite.write(strMemberData);
                fileWrite.close();
                JOptionPane.showMessageDialog(null, "회원가입이 완료되었습니다.");
            }
        } catch(FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "member.txt를 찾을 수 없습니다.");
        } catch(IOException ex) {
            
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member_MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxGame;
    private javax.swing.JCheckBox CheckBoxGolf;
    private javax.swing.JCheckBox CheckBoxReading;
    private javax.swing.JCheckBox CheckBoxSki;
    private javax.swing.JCheckBox CheckBoxSwimming;
    private javax.swing.JCheckBox CheckBoxTennis;
    private javax.swing.JRadioButton RadioBtnAssociate;
    private javax.swing.JRadioButton RadioBtnRegular;
    private javax.swing.JRadioButton RadioBtnStudent;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnOverlap;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
